version: '3.8'

services:
  redis_cluster:
    image: grokzen/redis-cluster:${REDIS_CLUSTER_VERSION}
    ports:
      - '7000-7005:7000-7005'
    environment:
      IP: 0.0.0.0
    container_name: ${REDIS_CLUSTER_CONTAINER_NAME}

networks:
    default:
        name: ${REDIS_BASIC_NETWORK}
